services:
  dockerpage:
    build: .
    container_name: docker-dashboard
    ports:
      - "5000:5000"
    volumes:
      # Mount Docker socket to access Docker daemon
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - FLASK_ENV=production
      - HOST_URL=192.168.6.3
      - ENABLE_STATS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: docker-dashboard-proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - dockerpage
  #   restart: unless-stopped
